Johnathon's file

Get the data run this before so that you can load in the data to the environment

```{r}

library(readxl)
X06_CAS_Predictive_Modeling_Case_Competition_Dataset <- read_excel("CAS-CaseComp/06 - CAS Predictive Modeling Case Competition- Dataset.xlsx")
View(X06_CAS_Predictive_Modeling_Case_Competition_Dataset)

```

Start and create the data

```{r}
set.seed(1)

df <- X06_CAS_Predictive_Modeling_Case_Competition_Dataset  # or readr::read_csv

# Basic hygiene

#df <- within(df, {
#  exposure <- pmax(exposure, 1e-8)
#})

# Train/valid split
idx <- sample(seq_len(nrow(df)), size = floor(0.8 * nrow(df)))
train <- df[idx, ]
valid <- df[-idx, ]


names(train)
```

1.  First model for generalized linear model

Format is glm(parameters=what to use, dataset, family=type of distribution to use)

```{r}
fit_freq <- glm(
  claims ~ (class + study + gpa + sprinklered + greek + off_campus + distance_to_campus + amount + risk_tier + coverage),
  
  data = train,
  family = poisson(link = "log"),
  offset = log(exposure)
)

summary(fit_freq)

# Overdispersion check (rule-of-thumb)
dispersion <- sum(residuals(fit_freq, type="pearson")^2) / fit_freq$df.residual
dispersion

```

```{r}
library(MASS)

fit_freq_nb <- glm.nb(
  n_claims ~ year + dorm_location + distance + sprinkler + greek + ... + offset(log(exposure)),
  data = train
)
summary(fit_freq_nb)
```
